//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.26 at 05:13:37 PM GMT 
//


package de.iritgo.aktera.webservices.journal;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="occurredAt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="primaryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="secondaryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="secondaryTypeText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="shortMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entry"
})
@XmlRootElement(name = "listJournalResponse")
public class ListJournalResponse {

    protected List<ListJournalResponse.Entry> entry;

    /**
     * Gets the value of the entry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListJournalResponse.Entry }
     * 
     * 
     */
    public List<ListJournalResponse.Entry> getEntry() {
        if (entry == null) {
            entry = new ArrayList<ListJournalResponse.Entry>();
        }
        return this.entry;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="occurredAt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="primaryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="secondaryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="secondaryTypeText" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="shortMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "occurredAt",
        "primaryType",
        "secondaryType",
        "secondaryTypeText",
        "message",
        "shortMessage",
        "source"
    })
    public static class Entry {

        protected long id;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar occurredAt;
        @XmlElement(required = true)
        protected String primaryType;
        @XmlElement(required = true)
        protected String secondaryType;
        @XmlElement(required = true)
        protected String secondaryTypeText;
        @XmlElement(required = true)
        protected String message;
        @XmlElement(required = true)
        protected String shortMessage;
        @XmlElement(required = true)
        protected String source;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the occurredAt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getOccurredAt() {
            return occurredAt;
        }

        /**
         * Sets the value of the occurredAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setOccurredAt(XMLGregorianCalendar value) {
            this.occurredAt = value;
        }

        /**
         * Gets the value of the primaryType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrimaryType() {
            return primaryType;
        }

        /**
         * Sets the value of the primaryType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrimaryType(String value) {
            this.primaryType = value;
        }

        /**
         * Gets the value of the secondaryType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSecondaryType() {
            return secondaryType;
        }

        /**
         * Sets the value of the secondaryType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSecondaryType(String value) {
            this.secondaryType = value;
        }

        /**
         * Gets the value of the secondaryTypeText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSecondaryTypeText() {
            return secondaryTypeText;
        }

        /**
         * Sets the value of the secondaryTypeText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSecondaryTypeText(String value) {
            this.secondaryTypeText = value;
        }

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessage(String value) {
            this.message = value;
        }

        /**
         * Gets the value of the shortMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShortMessage() {
            return shortMessage;
        }

        /**
         * Sets the value of the shortMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShortMessage(String value) {
            this.shortMessage = value;
        }

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSource(String value) {
            this.source = value;
        }

    }

}
