//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.26 at 05:13:37 PM GMT 
//


package de.iritgo.aktera.webservices.journal;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.iritgo.aktera.webservices.journal package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.iritgo.aktera.webservices.journal
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CountJournalResponse }
     * 
     */
    public CountJournalResponse createCountJournalResponse() {
        return new CountJournalResponse();
    }

    /**
     * Create an instance of {@link ListJournalRequest }
     * 
     */
    public ListJournalRequest createListJournalRequest() {
        return new ListJournalRequest();
    }

    /**
     * Create an instance of {@link ListJournalResponse.Entry }
     * 
     */
    public ListJournalResponse.Entry createListJournalResponseEntry() {
        return new ListJournalResponse.Entry();
    }

    /**
     * Create an instance of {@link CountJournalRequest }
     * 
     */
    public CountJournalRequest createCountJournalRequest() {
        return new CountJournalRequest();
    }

    /**
     * Create an instance of {@link ListJournalResponse }
     * 
     */
    public ListJournalResponse createListJournalResponse() {
        return new ListJournalResponse();
    }

}
