/**
 * This file is part of the Iritgo/Aktera Framework.
 *
 * Copyright (C) 2005-2011 Iritgo Technologies.
 * Copyright (C) 2003-2005 BueroByte GbR.
 *
 * Iritgo licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.31 at 10:53:26 AM GMT 
//

package de.iritgo.aktera.webservices.webservices;


import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.iritgo.aktera.webservices.webservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.iritgo.aktera.webservices.webservices
	 * 
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link EchoRequest }
	 * 
	 */
	public EchoRequest createEchoRequest()
	{
		return new EchoRequest();
	}

	/**
	 * Create an instance of {@link EchoResponse }
	 * 
	 */
	public EchoResponse createEchoResponse()
	{
		return new EchoResponse();
	}

	/**
	 * Create an instance of {@link PingRequest }
	 * 
	 */
	public PingRequest createPingRequest()
	{
		return new PingRequest();
	}

	/**
	 * Create an instance of {@link PongResponse }
	 * 
	 */
	public PongResponse createPongResponse()
	{
		return new PongResponse();
	}

}
