/**
 * This file is part of the Iritgo/Aktera Framework.
 *
 * Copyright (C) 2005-2011 Iritgo Technologies.
 * Copyright (C) 2003-2005 BueroByte GbR.
 *
 * Iritgo licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.12 at 09:35:17 AM GMT 
//

package de.iritgo.aktera.webservices.address;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Address">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="salutation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="division" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="homepage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contactNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNumberB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNumberBDD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNumberBF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNumberBM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNumberP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNumberPF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNumberPM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNumberVOIP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="remark" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address", propOrder =
{
				"id", "salutation", "firstName", "lastName", "company", "division", "position", "street", "postalCode",
				"city", "country", "email", "homepage", "contactNumber", "companyNumber", "phoneNumberB",
				"phoneNumberBDD", "phoneNumberBF", "phoneNumberBM", "phoneNumberP", "phoneNumberPF", "phoneNumberPM",
				"phoneNumberVOIP", "remark"
})
public class Address
{

	@XmlElement(required = true)
	protected String id;

	@XmlElement(required = true)
	protected String salutation;

	@XmlElement(required = true)
	protected String firstName;

	@XmlElement(required = true)
	protected String lastName;

	@XmlElement(required = true)
	protected String company;

	@XmlElement(required = true)
	protected String division;

	@XmlElement(required = true)
	protected String position;

	@XmlElement(required = true)
	protected String street;

	@XmlElement(required = true)
	protected String postalCode;

	@XmlElement(required = true)
	protected String city;

	@XmlElement(required = true)
	protected String country;

	@XmlElement(required = true)
	protected String email;

	@XmlElement(required = true)
	protected String homepage;

	@XmlElement(required = true)
	protected String contactNumber;

	@XmlElement(required = true)
	protected String companyNumber;

	@XmlElement(required = true)
	protected String phoneNumberB;

	@XmlElement(required = true)
	protected String phoneNumberBDD;

	@XmlElement(required = true)
	protected String phoneNumberBF;

	@XmlElement(required = true)
	protected String phoneNumberBM;

	@XmlElement(required = true)
	protected String phoneNumberP;

	@XmlElement(required = true)
	protected String phoneNumberPF;

	@XmlElement(required = true)
	protected String phoneNumberPM;

	@XmlElement(required = true)
	protected String phoneNumberVOIP;

	@XmlElement(required = true)
	protected String remark;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setId(String value)
	{
		this.id = value;
	}

	/**
	 * Gets the value of the salutation property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getSalutation()
	{
		return salutation;
	}

	/**
	 * Sets the value of the salutation property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setSalutation(String value)
	{
		this.salutation = value;
	}

	/**
	 * Gets the value of the firstName property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getFirstName()
	{
		return firstName;
	}

	/**
	 * Sets the value of the firstName property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setFirstName(String value)
	{
		this.firstName = value;
	}

	/**
	 * Gets the value of the lastName property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getLastName()
	{
		return lastName;
	}

	/**
	 * Sets the value of the lastName property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setLastName(String value)
	{
		this.lastName = value;
	}

	/**
	 * Gets the value of the company property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getCompany()
	{
		return company;
	}

	/**
	 * Sets the value of the company property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setCompany(String value)
	{
		this.company = value;
	}

	/**
	 * Gets the value of the division property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getDivision()
	{
		return division;
	}

	/**
	 * Sets the value of the division property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setDivision(String value)
	{
		this.division = value;
	}

	/**
	 * Gets the value of the position property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getPosition()
	{
		return position;
	}

	/**
	 * Sets the value of the position property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPosition(String value)
	{
		this.position = value;
	}

	/**
	 * Gets the value of the street property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getStreet()
	{
		return street;
	}

	/**
	 * Sets the value of the street property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setStreet(String value)
	{
		this.street = value;
	}

	/**
	 * Gets the value of the postalCode property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getPostalCode()
	{
		return postalCode;
	}

	/**
	 * Sets the value of the postalCode property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPostalCode(String value)
	{
		this.postalCode = value;
	}

	/**
	 * Gets the value of the city property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getCity()
	{
		return city;
	}

	/**
	 * Sets the value of the city property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setCity(String value)
	{
		this.city = value;
	}

	/**
	 * Gets the value of the country property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getCountry()
	{
		return country;
	}

	/**
	 * Sets the value of the country property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setCountry(String value)
	{
		this.country = value;
	}

	/**
	 * Gets the value of the email property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * Sets the value of the email property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setEmail(String value)
	{
		this.email = value;
	}

	/**
	 * Gets the value of the homepage property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getHomepage()
	{
		return homepage;
	}

	/**
	 * Sets the value of the homepage property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setHomepage(String value)
	{
		this.homepage = value;
	}

	/**
	 * Gets the value of the contactNumber property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getContactNumber()
	{
		return contactNumber;
	}

	/**
	 * Sets the value of the contactNumber property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setContactNumber(String value)
	{
		this.contactNumber = value;
	}

	/**
	 * Gets the value of the companyNumber property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getCompanyNumber()
	{
		return companyNumber;
	}

	/**
	 * Sets the value of the companyNumber property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setCompanyNumber(String value)
	{
		this.companyNumber = value;
	}

	/**
	 * Gets the value of the phoneNumberB property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getPhoneNumberB()
	{
		return phoneNumberB;
	}

	/**
	 * Sets the value of the phoneNumberB property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPhoneNumberB(String value)
	{
		this.phoneNumberB = value;
	}

	/**
	 * Gets the value of the phoneNumberBDD property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getPhoneNumberBDD()
	{
		return phoneNumberBDD;
	}

	/**
	 * Sets the value of the phoneNumberBDD property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPhoneNumberBDD(String value)
	{
		this.phoneNumberBDD = value;
	}

	/**
	 * Gets the value of the phoneNumberBF property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getPhoneNumberBF()
	{
		return phoneNumberBF;
	}

	/**
	 * Sets the value of the phoneNumberBF property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPhoneNumberBF(String value)
	{
		this.phoneNumberBF = value;
	}

	/**
	 * Gets the value of the phoneNumberBM property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getPhoneNumberBM()
	{
		return phoneNumberBM;
	}

	/**
	 * Sets the value of the phoneNumberBM property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPhoneNumberBM(String value)
	{
		this.phoneNumberBM = value;
	}

	/**
	 * Gets the value of the phoneNumberP property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getPhoneNumberP()
	{
		return phoneNumberP;
	}

	/**
	 * Sets the value of the phoneNumberP property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPhoneNumberP(String value)
	{
		this.phoneNumberP = value;
	}

	/**
	 * Gets the value of the phoneNumberPF property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getPhoneNumberPF()
	{
		return phoneNumberPF;
	}

	/**
	 * Sets the value of the phoneNumberPF property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPhoneNumberPF(String value)
	{
		this.phoneNumberPF = value;
	}

	/**
	 * Gets the value of the phoneNumberPM property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getPhoneNumberPM()
	{
		return phoneNumberPM;
	}

	/**
	 * Sets the value of the phoneNumberPM property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPhoneNumberPM(String value)
	{
		this.phoneNumberPM = value;
	}

	/**
	 * Gets the value of the phoneNumberVOIP property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getPhoneNumberVOIP()
	{
		return phoneNumberVOIP;
	}

	/**
	 * Sets the value of the phoneNumberVOIP property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPhoneNumberVOIP(String value)
	{
		this.phoneNumberVOIP = value;
	}

	/**
	 * Gets the value of the remark property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getRemark()
	{
		return remark;
	}

	/**
	 * Sets the value of the remark property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setRemark(String value)
	{
		this.remark = value;
	}

}
