//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.12 at 09:35:17 AM GMT 
//


package de.iritgo.aktera.webservices.address;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.iritgo.aktera.webservices.address package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.iritgo.aktera.webservices.address
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDefaultAddressStoreIdRequest }
     * 
     */
    public GetDefaultAddressStoreIdRequest createGetDefaultAddressStoreIdRequest() {
        return new GetDefaultAddressStoreIdRequest();
    }

    /**
     * Create an instance of {@link ListAddressPhoneNumbersRequest }
     * 
     */
    public ListAddressPhoneNumbersRequest createListAddressPhoneNumbersRequest() {
        return new ListAddressPhoneNumbersRequest();
    }

    /**
     * Create an instance of {@link ListAddressesRequest }
     * 
     */
    public ListAddressesRequest createListAddressesRequest() {
        return new ListAddressesRequest();
    }

    /**
     * Create an instance of {@link CountAddressesRequest }
     * 
     */
    public CountAddressesRequest createCountAddressesRequest() {
        return new CountAddressesRequest();
    }

    /**
     * Create an instance of {@link FindAddressByPhoneNumberResponse }
     * 
     */
    public FindAddressByPhoneNumberResponse createFindAddressByPhoneNumberResponse() {
        return new FindAddressByPhoneNumberResponse();
    }

    /**
     * Create an instance of {@link FindAddressByPhoneNumberRequest }
     * 
     */
    public FindAddressByPhoneNumberRequest createFindAddressByPhoneNumberRequest() {
        return new FindAddressByPhoneNumberRequest();
    }

    /**
     * Create an instance of {@link ListAddressPhoneNumbersResponse }
     * 
     */
    public ListAddressPhoneNumbersResponse createListAddressPhoneNumbersResponse() {
        return new ListAddressPhoneNumbersResponse();
    }

    /**
     * Create an instance of {@link ListAddressStoresResponse.AddressStore }
     * 
     */
    public ListAddressStoresResponse.AddressStore createListAddressStoresResponseAddressStore() {
        return new ListAddressStoresResponse.AddressStore();
    }

    /**
     * Create an instance of {@link CountAddressesResponse }
     * 
     */
    public CountAddressesResponse createCountAddressesResponse() {
        return new CountAddressesResponse();
    }

    /**
     * Create an instance of {@link GetAddressRequest }
     * 
     */
    public GetAddressRequest createGetAddressRequest() {
        return new GetAddressRequest();
    }

    /**
     * Create an instance of {@link GetDefaultAddressStoreNameRequest }
     * 
     */
    public GetDefaultAddressStoreNameRequest createGetDefaultAddressStoreNameRequest() {
        return new GetDefaultAddressStoreNameRequest();
    }

    /**
     * Create an instance of {@link ListAddressPhoneNumbersResponse.PhoneNumber }
     * 
     */
    public ListAddressPhoneNumbersResponse.PhoneNumber createListAddressPhoneNumbersResponsePhoneNumber() {
        return new ListAddressPhoneNumbersResponse.PhoneNumber();
    }

    /**
     * Create an instance of {@link GetDefaultAddressStoreIdResponse }
     * 
     */
    public GetDefaultAddressStoreIdResponse createGetDefaultAddressStoreIdResponse() {
        return new GetDefaultAddressStoreIdResponse();
    }

    /**
     * Create an instance of {@link ListAddressStoresResponse }
     * 
     */
    public ListAddressStoresResponse createListAddressStoresResponse() {
        return new ListAddressStoresResponse();
    }

    /**
     * Create an instance of {@link GetAddressResponse }
     * 
     */
    public GetAddressResponse createGetAddressResponse() {
        return new GetAddressResponse();
    }

    /**
     * Create an instance of {@link de.iritgo.aktera.webservices.address.Address }
     * 
     */
    public de.iritgo.aktera.webservices.address.Address createAddress() {
        return new de.iritgo.aktera.webservices.address.Address();
    }

    /**
     * Create an instance of {@link ListAddressesResponse }
     * 
     */
    public ListAddressesResponse createListAddressesResponse() {
        return new ListAddressesResponse();
    }

    /**
     * Create an instance of {@link GetDefaultAddressStoreNameResponse }
     * 
     */
    public GetDefaultAddressStoreNameResponse createGetDefaultAddressStoreNameResponse() {
        return new GetDefaultAddressStoreNameResponse();
    }

    /**
     * Create an instance of {@link ListAddressStoresRequest }
     * 
     */
    public ListAddressStoresRequest createListAddressStoresRequest() {
        return new ListAddressStoresRequest();
    }

    /**
     * Create an instance of {@link ListAddressesResponse.Address }
     * 
     */
    public ListAddressesResponse.Address createListAddressesResponseAddress() {
        return new ListAddressesResponse.Address();
    }

}
