//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.12 at 09:35:17 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://aktera.iritgo.de/webservices/address", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.iritgo.aktera.webservices.address;
